import { FastifyInstance } from "fastify";
import { importCurriculum } from "../../../../packages/db/scripts/import-curriculum";

export async function factoryRoutes(app: FastifyInstance) {
  const authenticate = { preHandler: [app.authenticate] };

  // POST /api/v1/factory/generate
  // This simulates the LLM generation step for the Curriculum Factory.
  app.post("/generate", authenticate, async (request, reply) => {
    const { grade, subjectCode, chapterTitle } = request.body as any;

    if (!grade || !subjectCode || !chapterTitle) {
      return reply.code(400).send({ success: false, message: "Missing required fields" });
    }

    // Simulate AI thinking delay (1.5 seconds)
    await new Promise(resolve => setTimeout(resolve, 1500));

    // We generate a deterministic AI payload that mirrors the JSON schema exactly.
    // In a real scenario, this is where we call OpenAI or Gemini with a LangChain Agent.
    const generatedPayload = {
      classes: [
        {
          grade: Number(grade),
          subjects: [
            {
              code: subjectCode,
              name: subjectCode === "SCI7" ? "Science" : "Subject",
              iconUrl: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
              chapters: [
                {
                  title: chapterTitle,
                  summary: `This chapter covers the fundamental principles of ${chapterTitle}. It explores how these concepts apply to the natural world and everyday life.`,
                  learningObjectives: [
                    "Understand the core mechanism",
                    "Identify key components and variables",
                    "Apply the concept to real-world scenarios",
                    "Analyze the environmental impact"
                  ],
                  keywords: ["Mechanism", "Energy", "Transformation", "System"],
                  difficultyLevel: "MEDIUM",
                  orderIndex: 1,
                  concepts: Array.from({ length: 5 }).map((_, i) => ({
                    name: `Concept ${i + 1}: Core Principle`,
                    explanation: `Detailed explanation of Concept ${i + 1} generated by AI. It breaks down the complex theory into simple, digestible facts.`,
                    realLifeExample: `Applying Concept ${i + 1} in a modern city context, such as managing a household budget or driving a car.`,
                    villageExample: `Applying Concept ${i + 1} in a rural setting, such as measuring crop yield or water conservation techniques.`,
                    activities: [
                      { title: `Hands-on Activity for Concept ${i + 1}` }
                    ],
                    quizzes: [
                      { title: `Quiz Question 1 for Concept ${i + 1}` },
                      { title: `Quiz Question 2 for Concept ${i + 1}` }
                    ],
                    projects: [
                      { title: `Village Impact Project: ${chapterTitle} App`, category: "Science Project" }
                    ],
                    skills: [
                      { name: "Analytical Thinking", description: "Breaking down complex problems." },
                      { name: "Scientific Inquiry", description: "Asking questions and investigating." }
                    ],
                    careers: [
                      { name: "Research Scientist", category: "SCIENCE", description: "Conducts scientific research." },
                      { name: "Environmental Engineer", category: "ENGINEERING", description: "Designs solutions for environmental issues." }
                    ]
                  }))
                }
              ]
            }
          ]
        }
      ]
    };

    return reply.send({
      success: true,
      message: "Curriculum generated via AI successfully.",
      data: generatedPayload
    });
  });

  // POST /api/v1/factory/approve
  // Takes the approved payload and saves it forever.
  app.post("/approve", authenticate, async (request, reply) => {
    try {
      const payload = request.body;
      const stats = await importCurriculum(payload, app.prisma as any);
      return reply.send({
        success: true,
        message: "Curriculum approved and published to Knowledge Graph successfully.",
        data: stats
      });
    } catch (error: any) {
      request.log.error(error);
      return reply.status(500).send({ success: false, message: error.message });
    }
  });
}
